apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: lestsencrypt
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: wesley@schoolofnet.com
    privateKeySecretRef:
      name: lestsencrypt-tls
    solvers:
    - http01:
      ingress:
        class: nginx